# Generated by Django 5.1.15 on 2026-09-23 14:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EnergyType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('electricity', '电'), ('coal', '煤'), ('steam', '蒸汽')], max_length=32, unique=True, verbose_name='能源类型')),
                ('name', models.CharField(max_length=32, verbose_name='名称')),
                ('unit', models.CharField(max_length=16, verbose_name='计量单位')),
                ('coal_equiv', models.DecimalField(decimal_places=6, default=0, max_digits=10, verbose_name='折标煤系数')),
                ('color', models.CharField(default='#38bdf8', max_length=16, verbose_name='图表颜色')),
                ('order', models.IntegerField(default=0, verbose_name='展示排序')),
            ],
            options={
                'verbose_name': '能源类型',
                'verbose_name_plural': '能源类型',
                'ordering': ['order', 'kind'],
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32, unique=True, verbose_name='工段编号')),
                ('name', models.CharField(max_length=64, verbose_name='工段名称')),
                ('order', models.IntegerField(default=0, verbose_name='展示排序')),
                ('active', models.BooleanField(default=True, verbose_name='启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '工段',
                'verbose_name_plural': '工段',
                'ordering': ['order', 'code'],
            },
        ),
        migrations.CreateModel(
            name='Reading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ts', models.DateTimeField(db_index=True, verbose_name='采集时间')),
                ('amount', models.DecimalField(decimal_places=3, default=0, max_digits=14, verbose_name='用量')),
                ('output', models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True, verbose_name='产量')),
                ('energy_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='board.energytype', verbose_name='能源类型')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='board.section', verbose_name='工段')),
            ],
            options={
                'verbose_name': '能耗读数',
                'verbose_name_plural': '能耗读数',
                'ordering': ['-ts'],
                'indexes': [models.Index(fields=['section', 'energy_type', 'ts'], name='board_readi_section_0cab15_idx')],
            },
        ),
        migrations.CreateModel(
            name='Quota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(choices=[('day', '日'), ('month', '月')], default='day', max_length=16, verbose_name='考核周期')),
                ('limit_amount', models.DecimalField(decimal_places=3, default=0, max_digits=14, verbose_name='周期定额')),
                ('warn_ratio', models.DecimalField(decimal_places=2, default=0.9, max_digits=4, verbose_name='预警阈值比例')),
                ('effective_from', models.DateField(blank=True, null=True, verbose_name='生效日期')),
                ('energy_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotas', to='board.energytype', verbose_name='能源类型')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotas', to='board.section', verbose_name='工段')),
            ],
            options={
                'verbose_name': '能耗定额',
                'verbose_name_plural': '能耗定额',
                'ordering': ['section', 'energy_type', 'period'],
                'constraints': [models.UniqueConstraint(fields=('section', 'energy_type', 'period'), name='uniq_quota_section_energy_period')],
            },
        ),
    ]
